[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "/server/index.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
