services:
  - type: web
    name: europe-travel-planner
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm run start:postgres
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: europe-travel-db
          property: connectionString
    healthCheckPath: /api/itineraries
