services:
  - type: web
    name: europe-travel-planner
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/itineraries
