name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # 当推送到 master 分支时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # 需要写权限来推送到 gh-pages 分支

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: 安装依赖
        run: |
          cd client
          npm ci

      - name: 构建项目
        run: |
          cd client
          npm run build

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
          publish_branch: gh-pages
          cname: false # 如果你有自定义域名，设置为域名；否则设置为 false
